In [20]:
import numpy as np

### isNaN
def isNaN(num):
    return num != num


### type 인자 예외처리
def trycatch_type(type):
    type_allowed = ["none", "drift", "trend"]
    if type not in type_allowed:
        raise ValueError

        
### select 인자 예외처리
def trycatch_selectlags(selectlags):
    selectlags_allowed = ["Fixed", "AIC", "BIC"]
    if selectlags not in selectlags_allowed:
        raise ValueError
    
    
    
### ADF Test    
def ur_df(y, type, lags, selectlags):
    y = np.array(y)
    
    # type 인자 예외처리
    try:
        trycatch_type(type)
    except ValueError:
         print('type 인자에 잘못된 값을 넣었습니다!')
        
    # select 인자 예외처리
    try:
        trycatch_selectlags(selectlags)
    except ValueError:
         print('selectlags 인자에 잘못된 값을 넣었습니다!')
    
    
    if (np.size(y, 1) > 1)
        
        
        
        
ur_df("none", "Fixed")

In [243]:
import numpy as np

import trycatch
# import difference
# import embed


# create a differenced series
def difference(dataset, interval=1):
    diff = list()
    for i in range(interval, len(dataset)):
        value = dataset[i] - dataset[i - interval]
        diff.append(value)
    return diff

# Embeds the time series x into a low-dimensional Euclidean space.
def embed(x, dimension = 1):
    x = np.array(x)
    n = np.size(x)
    trycatch_embed1(dimension)   # if dimension < 1
    trycatch_embed2(dimension, n)   # if dimension > n

    m = n - dimension + 1
    nrows = n - dimension + 1
    ncols = dimension
    res = np.zeros((nrows, ncols))
    
    for i in range(0, m):
        rangeList = 0
        if dimension > 1:
            rangeList = list(range(i,(i+dimension)))
            rangeList = sorted(rangeList, reverse=True)
        res[i,:] = x[rangeList]
    
    return res



   
    
### ADF Test    
y = [0.63879800,    0.06408028,    0.48604897,   -1.58697346,    0.30119843,
     0.52400797,   -1.00631168,   -1.71601178,   -1.11615800,   -1.95483223,
     1.25138559,   -0.03914765,    0.29340561,   -0.26979114,   -2.19076537,
    -0.41272851,    0.82519253,   -1.58494589,   -0.59528146,   -1.13331441,
    -0.02561859,    1.04058840,   -0.15183498,   -1.72953257,   -0.43774242,
    -0.35912475,   -0.92478409,    0.36345445,   -2.89838335,    0.17969599,
    -0.94153923,   -0.92721559,    0.35548862,   -1.37925653,   -0.33343839,
     1.77508187,    0.93348700,    0.34664076,   -0.13148586,   -0.99556941,
     0.22235388,    0.19082698,   -0.68070331,   -0.07998095,   -0.05132541,
     0.27217320,    0.79859116,   -0.26117486,   -0.25679888,   -1.08725721,
     0.06868815,   -0.22138414,    2.04232367,   -0.38412594,    3.00486151,
    -0.24512904,   -0.71143873,   -0.15900114,    1.59604924,    0.26362804,
    -0.41155883,   -0.17556811,   -1.40720515,    0.64582375,   -1.78894285, 
     1.82167080,   -0.98903683,    0.72921922,   -0.77866089,    0.82266470,
    -0.48025938,   -0.47855899,   -1.39339553,    1.08481269,   -1.45591627,
     0.27207592,    2.06500493,    0.70595652,    1.31198462,   -0.55897218,
    -0.85137257,    1.81072471,    1.70872944,    0.26915856,   -0.75111565,
    -0.78609945,    0.14488176,    0.04472911,   -0.39526862,   -1.49188673,
     1.12522571,   -1.29881997,   -1.07821846,   -0.34596076,    0.61521773,
     0.41804365,   -1.32955607,    0.38376991,    0.76712652,   -0.58262202]


y = np.array(y)
type = "none"
selectlags = "Fixed"
lags = 1

trycatch_type(type)     # type 인자 예외처리
trycatch_selectlags(selectlags)     # select 인자 예외처리
trycatch_univariate(y)     # y is not a vector or univariate time series.
trycatch_NA(y)     # y is not a vector or univariate time series.
        

# y = as.vector(y)     # 구현 불필요
lag = int(lags)


### Lags must be set to an non negative integer value.


        
# CALL = match.call()     # 구현 불필요
# DNAME = deparse(substitute(y))     # 구현 불필요
# x.name = deparse(substitute(y))     # 구현 불필요
lags = lags + 1

z = difference(y, interval = 1)
n = np.size(z)
x = embed(z, lags)
z_diff = x[:,1]
z_lag_1 = y[range(lags, n)]
tt = list(range(lags, n))

if lags > 1:
    if selectlags != "Fixed':
        critRes = [None]*lags
        
#ur_df("none", "Fixed")

array([[ 4.21968690e-01, -5.74717720e-01],
       [-2.07302243e+00,  4.21968690e-01],
       [ 1.88817189e+00, -2.07302243e+00],
       [ 2.22809540e-01,  1.88817189e+00],
       [-1.53031965e+00,  2.22809540e-01],
       [-7.09700100e-01, -1.53031965e+00],
       [ 5.99853780e-01, -7.09700100e-01],
       [-8.38674230e-01,  5.99853780e-01],
       [ 3.20621782e+00, -8.38674230e-01],
       [-1.29053324e+00,  3.20621782e+00],
       [ 3.32553260e-01, -1.29053324e+00],
       [-5.63196750e-01,  3.32553260e-01],
       [-1.92097423e+00, -5.63196750e-01],
       [ 1.77803686e+00, -1.92097423e+00],
       [ 1.23792104e+00,  1.77803686e+00],
       [-2.41013842e+00,  1.23792104e+00],
       [ 9.89664430e-01, -2.41013842e+00],
       [-5.38032950e-01,  9.89664430e-01],
       [ 1.10769582e+00, -5.38032950e-01],
       [ 1.06620699e+00,  1.10769582e+00],
       [-1.19242338e+00,  1.06620699e+00],
       [-1.57769759e+00, -1.19242338e+00],
       [ 1.29179015e+00, -1.57769759e+00],
       [ 7.

In [220]:



import trycatch


    
y = np.array( [0.63879800,    0.06408028,    0.48604897,   -1.58697346,    0.30119843,
               0.52400797,   -1.00631168,   -1.71601178,   -1.11615800,   -1.95483223])

print(embed(y, 2))

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[ 0.06408028  0.638798  ]
 [ 0.48604897  0.06408028]
 [-1.58697346  0.48604897]
 [ 0.30119843 -1.58697346]
 [ 0.52400797  0.30119843]
 [-1.00631168  0.52400797]
 [-1.71601178 -1.00631168]
 [-1.116158   -1.71601178]
 [-1.95483223 -1.116158  ]]


In [161]:
y = np.array( [[0.63879800,    0.06408028,    0.48604897,   -1.58697346,    0.30119843],
               [0.52400797,   -1.00631168,   -1.71601178,   -1.11615800,   -1.95483223]])
print(np.size(y))
print([5]*5)
print(y)
print(1)
m = 2

print(y[1,:])

10
[5, 5, 5, 5, 5]
[[ 0.638798    0.06408028  0.48604897 -1.58697346  0.30119843]
 [ 0.52400797 -1.00631168 -1.71601178 -1.116158   -1.95483223]]
1
[ 0.52400797 -1.00631168 -1.71601178 -1.116158   -1.95483223]


In [136]:
import numpy as np
A = np.zeros([2,2])
A[:,1]

array([0., 0.])

In [110]:
rscript = """
matrix(0, n - dimension + 1L, dimension * m)
"""

from pyensae.languages import r2python
print(r2python(rscript, pep8=True))

matrix(0, n - dimension + 1, dimension * m)

